app/forum/__init__.py
# -*- coding: UTF-8 -*-
from flask import Blueprint

__author__ = 'Ivan'

forum = Blueprint('forum', __name__)

from . import views

app/forum/views.py
# -*- coding: utf-8 -*-
import json
from datetime import datetime

from flask import render_template, jsonify, request
from flask.ext.login import login_required, current_user
from flask.ext.restful import abort, marshal

from app.class_authority_util import user_course_authority
from app.dao.thread_dao import ForumDao, ThreadDao, ForumThreadRelationDao, ThreadPostDao, ThreadLikeDao, \
    ThreadRequestDao
from app.dao.user_dao import UserDao
from app.forum.util import is_forum_admin
from app.models import Thread, ForumThreadRelation, ThreadPost, ThreadLike, ThreadRequest
from app.user.views import thread_fields
from app.util.HTMLSpider import ThreadHtmlPareser
from tasks import  task_get_article,task_get_jinshu_articles, task_get_lcode_articles
from . import forum

__author__ = 'Ivan'



#
# @forum.route("/<int:forum_id>/spider/jianshu/one/<string:id>")
# @login_required
# def jianshu_spider(forum_id,id):
#     task = task_get_article.delay(id,current_user.id,forum_id)
#     return jsonify(task=task.id)
#
# @forum.route("/spider/jianshu/list/<int:start>/<int:end>")
# @login_required
# def jianshu_list_spider(start,end):
#     if current_user.is_super_admin():
#         task = task_get_jinshu_articles.delay(start,end)
#         return jsonify(task=task.id)
#
#     return jsonify(message=u"无权限")
#
#
# @forum.route("/<int:forum_id>/spider/lcode/list")
# @login_required
# def lcode_spider(forum_id):
#
#     task=task_get_lcode_articles.delay(current_user.id,forum_id)
#
#     return jsonify(task=task.id)


@forum.route("/spider",methods=["POST"])
@login_required
def spider():

    params = request.get_json();

    forum_id = params.get("forum_id")
    site = params.get("site")
    url = params.get("url")

    task = task_get_article.delay(site,url,current_user.id,forum_id)

    return jsonify(success=1,task=task.id)





@forum.route("/")
def index():

    list =UserDao().find_top10_thread_writer()
    forums = ForumDao().find_all()

    is_admin=False
    if current_user.is_authenticated():
        is_admin=current_user.is_super_admin()

    return render_template("forum/index.html",forums=forums,forum_id=0,top_writer=list,is_admin=is_admin)

@forum.route("/<int:id>")
def detail(id):

    dao =ForumDao()
    forum = dao.get(id);

    if forum is None:
        return  abort(404)

    forums = ForumDao().find_all()
    list =UserDao().find_top10_thread_writer()
    return render_template("forum/index.html",forums=forums,forum_id=forum.id,top_writer=list,is_admin=is_admin(forum))

    # return render_template('forum/detail.html',forum=forum,is_admin=is_admin(forum),forums=dao.find_all())



@forum.route("/<int:id>/hot/thread")
def forum_hot_thread(id):

     threads = ThreadDao().find_forum_hot_threads(id,10)
     result = json.dumps(marshal(threads,thread_fields))

     return result



############################投稿模块####################################################

@forum.route("/<int:id>/thread/submit")
@login_required
def forum_thread_submit(id):
     return render_template('forum/submit.html',forum_id = id)


@forum.route("/<int:id>/thread/submit/result")
@login_required
def forum_thread_submit_result(id):
    return render_template('forum/submit-result.html',forum_id = id)


@forum.route("/thread/submit/request",methods=['POST'])
@login_required
def forum_thread_submit_request():

    json = request.get_json();
    title = json.get("title")
    url = json.get("url")
    thread_id = json.get("threadId")
    forum_id = json.get("forumId")


    thread_dao =ThreadDao();
    thread = thread_dao.get(thread_id)
    if thread is None:
        return jsonify(success=True,message=u'文章不存在')

    forum_dao =ForumDao()

    forum = forum_dao.get(forum_id)

    if forum is None:
        return jsonify(success=True,message=u'栏目不存在')



    auth = is_admin(forum)
    if auth:
        relation = ForumThreadRelation(forum_id=forum_id,thread_id=thread_id,created_time=datetime.now())
        ForumThreadRelationDao().save(relation)

    else:
        thread_request =  ThreadRequest(title=title,url=url,
                                        thread_id=thread_id,
                                        forum_id=forum_id,
                                        request_user_id=current_user.id,
                                        request_time=datetime.now(),
                                        status=0)

        ThreadRequestDao().save(thread_request)

    return jsonify(success=True)



############################文章模块####################################################

@forum.route("/thread/<int:id>")
def thread_detail(id):

    thread_dao = ThreadDao()
    thread = thread_dao.get(id)

    if thread is None:
        return abort(404);



    auth=False
    if current_user.is_authenticated(): #已经登录
        auth = current_user.is_super_admin() or (current_user.id==thread.user_id)
        if auth:
            content = thread.content #管理员或者作者本人直接显示原始内容
        else:
            post_count=ThreadPostDao().get_thread_user_post_count(current_user.id,thread.id)
            if post_count>0:
                content = thread.content
            else:
                content = ThreadHtmlPareser().show(thread.content)
    else:
        content = ThreadHtmlPareser().show(thread.content)

    thread_count = thread_dao.get_user_thread_count(thread.user_id)
    return render_template("forum/thread-detail.html",thread=thread,auth=auth,thread_count=thread_count,content=content)


@forum.route("/<int:id>/thread/write")
@login_required
def thread_write(id):
    thread={}
    return render_template("forum/write.html",forum_id=id,thread=thread,action='create',thread_type=1)


@forum.route("/thread/<int:id>/update")
@login_required
def thread_update(id):
    thread = ThreadDao().get(id)
    return render_template("forum/write.html",thread=thread,action='update')


@forum.route("/thread/create",methods=['POST'])
@login_required
def thread_create():

    form = request.get_json()


    title = form.get('title')
    content = form.get('content');
    brief = form.get("brief")
    is_original = form.get("is_original")
    thread_type = form.get("thread_type")


    if thread_type==1:

        forum_id = form.get("forumId")
        forum_dao = ForumDao()
        forum = forum_dao.get(forum_id)

        if forum.is_normal_forum()==False: #普通板块

            is_admin=is_forum_admin(current_user.id,forum.admins)
            if is_admin==False:
                return jsonify(result=False,message=u'您暂无权限发表文章')


    htmlparser = ThreadHtmlPareser()
    htmlparser.pasert(content)

    img_links=None
    if  len(htmlparser.imgs)>0:
        img_links = ",".join(htmlparser.imgs)


    thread_dao = ThreadDao()

    thread = Thread(
                title=title,
                content=content,
                imgs=img_links,
                user_id=current_user.id,
                ip_address=request.remote_addr,
                created_time=datetime.now(),
                read_count=1,
                is_original=is_original,
                brief=brief,
                status =1,
                thread_type=thread_type
                )

    thread_dao.save(thread)


    if thread_type==1: # 在栏目里面发帖才保存中间表
        #保存中间表
        relation= ForumThreadRelation(forum_id=forum_id,thread_id=thread.id,
                                      created_time=datetime.now())
        ForumThreadRelationDao().save(relation)
        #数量加1
        forum.thread_count+=1
        forum_dao.save(forum)



    return  jsonify(result=True,message='success')


@forum.route("/thread/modify",methods=['POST'])
@login_required
def thread_modify():
    form = request.get_json()

    thread_id = form.get("threadId")
    title = form.get('title')
    content = form.get('content')
    brief = form.get("brief")
    is_original = form.get("is_original")

    thread_dao = ThreadDao()

    thread = thread_dao.get(thread_id)

    if thread is None:
        return jsonify(result=False,message='文章不存在')

    auth = current_user.is_super_admin() or (current_user.id==thread.user_id)

    if auth==False:
        return jsonify(result=False,message='无权限修改')


    thread.title=title
    thread.content=content
    thread.brief=brief
    thread.is_original=is_original
    thread.last_update_time=datetime.now()

    thread_dao.save(thread)

    return jsonify(result=True,message='success')


@forum.route("/thread/read/<int:id>")
def thread_read(id):

     thread = ThreadDao().get(id)

     thread.read_count += 1
     ThreadDao().save(thread)

     return jsonify(success=1,message='success')

@forum.route("/thread/delete/<int:id>",methods=['POST'])
@login_required
def thread_delete(id):

    dao =ThreadDao();
    thread = dao.get(id)

    auth = current_user.is_super_admin() or (current_user.id==thread.user_id)

    if auth==False:
        return jsonify(success=0,message='无权限删除')

    thread.status =-1;
    dao.save(thread)

    return jsonify(success=1,message='success')


############# 评论 ###########

@forum.route("/thread/post/create",methods=['POST'])
@login_required
def thread_post_create():

    json = request.get_json()

    course_id = json.get("courseId")
    thread_id = json.get('threadId')
    content = json.get('content')


    if course_id >0:
        course_id = int(course_id)
        course_can_play =user_course_authority(course_id)


        if course_can_play == False:
            return jsonify(success=0,message=u'您还不是学员，没有权限提交问题')



    thread_post = ThreadPost(content=content,
                             thread_id=thread_id,
                             class_id=course_id,
                             user_id=current_user.id,
                             ip_address=request.remote_addr,
                             created_time=datetime.now(),
                             status=1)

    ThreadPostDao().save(thread_post)

    thread_dao = ThreadDao();

    thread = thread_dao.get_or_404(thread_id)
    thread.last_comment_time = datetime.now()
    thread.reply_count += 1

app/templates/forum/detail.html
{% extends "base_new.html" %}

{% block title %}{{ forum.title }} 菜鸟窝-国内领先专业的移动开发IT技能在线教育平台{% endblock %}
{% block description %} {{ forum.intro }}{% endblock %}


{% block main_block %}

<div id="content-container" class="container">

        <div class="group-header section-white hidden-xs">

            <div class="media">

                <div class="media-left">

                    <a href="#">
                        <img src="{{ forum.logo_url }}" alt="{{ forum.title }}">
                    </a>
                </div>
                <div class="media-body">

                    <h2 class="media-heading">
                        {{ forum.title }}

                    </h2>
                    <div class="subtitle hidden-xs">
                        {{ forum.intro }}

                    </div>

                    <div class="media-metas">

                        <span> <span class="mr5">{{ forum.thread_count }}</span> 篇文章</span>

                        <span class="mlm  cniao-share top">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon icon-share3"></i> 分享</a>

                            <div class="dropdown-menu  js-social-share-params"
                                 style="padding: 10px 0px !important;"
                                                     data-title="{{ forum.title }}"
                                                     data-summary="{{ forum.intro  }}"
                                                     data-message="这里很多技术干货,我和小伙伴们都在这里混"
                                                     data-url="{{ url_for('forum.detail',id=forum.id,_external=True) }}"
                                                    data-invite-code="{% if current_user.is_authenticated() %}{{ current_user.get_unique_code() }}{% else %}0{% endif %}"
                                                     data-picture="{{ forum.logo_url }}">
                                                    <a href="javascript:;" class="js-social-share" data-cmd="qq" title="分享到QQ好友" data-share="qq"><i class="icon icon-qq"></i></a>
                                                    <a href="javascript:;" class="js-social-share" data-cmd="weixin" title="分享到微信" data-share="weixin" data-qrcode-url=""><i class="icon icon-weixin"></i></a>
                                                    <a href="javascript:;" class="js-social-share" data-cmd="tsina" title="分享到新浪微博" data-share="weibo"><i class="icon icon-weibo"></i></a>

                                                    <a href="javascript:;" class="js-social-share" data-cmd="qzone" title="分享到QQ空间" data-share="qzone"><i class="icon icon-icon-qzone-full"></i></a>

                            </div>

                        </span>

{#                        <span class=" mlm btn btn-success follow">#}
{##}
{#                            <a href="">#}
{##}
{#                                <i class="icon icon-plus"></i>#}
{#                                <span>添加关注</span>#}
{#                            </a>#}
{##}
{#                        </span>#}

                            <span class="mlm">
                                <a href="{{ url_for('.forum_thread_submit',id=forum.id) }}" class="">

                                            <i class="icon icon-plug-add-3"></i>
                                            投稿
                                </a>
                            </span>

                         {% if current_user.is_authenticated() and is_admin  %}

                            <span  class="mlm">
                                <a href="{{ url_for('.thread_write',id=forum.id) }}" target="_blank" >

                                    <i class="icon icon-write"></i>
                                    写文章
                                </a>

                             </span>
                        {% endif %}




                    </div>

                </div>


            </div>

        </div>

        <div class="row">

            <div class="col-md-9 group-main">

                <div class="panel panel-default">

                    <div class="panel-body">

                        <div class="clearfix mbl">

                            <ul class="nav nav-tabs">

                                <li class="active js-thread-type"
                                data-is-hot="0">
                                    <a class="js-nav"

                                       href="javascript:void(0)">全部</a>
                                </li>

                                <li class="js-thread-type"
                                    data-is-hot="1"
                                    >
                                    <a class="js-nav"
                                       href="javascript:void(0)">热门</a>
                                </li>




                                <li class="dropdown" >
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="font-size: 12px">
                                        <span class="text-muted">排序：</span>
                                          <span class="js-current-thread-sort">最新发帖</span>
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li class="active js-thread-sort" data-order-by="0"><a class="js-nav" href="javascript:void(0)">最新发帖</a></li>
                                        <li class="js-thread-sort" data-order-by="1"><a class="js-nav" href="avascript:void(0)">最后回复</a></li>
                                    </ul>
                                </li>
                            </ul>

                        </div>

                            <div
                            class="js-thread-query-params"
                            data-target-id="{{ forum.id }}"
                            data-target-type="forum"
                            data-is-admin="{% if is_admin %}1{% else %}0{% endif %}"
                            > </div>

                            <div id="thread-list">

                            </div>

                            <nav class="text-center">

                                <a class="btn btn-rectangle btn-success js-load-more hidden">浏览更多</a>
                            </nav>
{#                            <nav class=" text-center hidden">#}
{#                                <ul class="pagination" id="pagination-thread">#}
{##}
{#                                </ul>#}
{#                            </nav>#}


                    </div>
                </div>

            </div>
            <div class="col-md-3 group-sid">

                <form class="mbl hidden" action="" method="get">
                    <div class="search-with-btn">
                        <input type="text" class="form-control" placeholder="搜索" name="keyWord">
                        <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                    </div>
                </form>



                <div class="panel panel-default">
                    <div class="panel-heading"><h3 class="panel-title">舵主</h3></div>
                    <div class="panel-body">

                        {% for admin in forum.admins %}

                            <div class="media group-item">
                            <div class="media-left">
                                <a class="js-user-card"  href="{{url_for('user.detail',id=admin.user.id) }}" data-user-id="{{ admin.user.id }}" data-card-url="{{ url_for('user.user_public_info',id=admin.user.id) }}">

                                    {% if admin.user.logo_url is none or admin.user.logo_url=='' %}
                                        <img class="avatar-sm" src="{{ url_for('static', filename='images/default_head.jpeg') }}">
                                    {% else %}
                                        <img class="avatar-sm" src="{{ admin.user.logo_url }}">
                                    {% endif %}
                                </a>

                            </div>
                            <div class="media-body">
                                <div><a class="gray-darker" href="javascript:void(0)" title="{{ admin.user.username }}">{{ admin.user.username }}</a></div>
                                <span class="text-sm gray-medium">{% if admin.type==1 %}总舵主 {% else %} 二当家 {% endif %} </span>
                            </div>
                        </div>
                        {% endfor %}


                    </div>
                </div>


                <div class="panel panel-default">
                    <div class="panel-heading"><h3 class="panel-title">热门专题</h3></div>

                    <div class="panel-body">

                        {% for f in forums %}

                            {% if f.id !=forum.id %}

                                 <div class="media group-item">
                                    <div class="media-left">
                                     <img src="{{ f.logo_url }}"
                                                        class="avatar-sm">

                                    </div>
                                    <div class="media-body">
                                        <div><a class="title" href="{{ url_for("forum.detail",id=f.id) }}" title="{{ f.title }}">{{ f.title }}</a></div>
                                    </div>
                             </div>

                            {% endif %}

                        {% endfor %}

                    </div>



                </div>

            </div>

        </div>

</div>



{% endblock %}

{% block custom_js_block %}

        <script type="text/javascript">
        var app={};
        app.debug = true;
        app.jsPaths={};
        app.global_script='path-js/global-config';
        app.controller='app/forum';
        app.mainScript = 'path-js/app';
        seajs.use(app.mainScript);

    </script>
{% endblock %}

app/templates/forum/submit-result.html
{% extends "base_new.html" %}

{% block title %}

    感谢分享
    菜鸟窝-国内领先专业的移动开发IT技能在线教育平台

{% endblock %}
{% block description %}{% endblock %}


{% block main_block %}

<div id="content-container" class="container">


    <div class="row">

        <div class="col-md-12">


                <div class="submit-section cniao-section">


                      <div class="text-center">


                          <p>
                              <i class="icon icon-smell2" style="font-size: 200px; color:#f1f1f1 "></i>
                          </p>

                          <p style="font-size: 16px;font-weight:500;">
                              感谢您的分享,有的投稿我们会做得更好
                          </p>
                          <p style="font-size: 16px">
                              <a href="{{ url_for(".detail",id=forum_id) }}">返回栏目</a>
                          </p>



                      </div>


                </div>

        </div>
    </div>


</div>



{% endblock %}

{% block custom_js_block %}

    <script type="text/javascript">
     var CKEDITOR_BASEPATH ="/static/libs/ckeditor/4.4.8/";
        var app={};
        app.jsPaths={};
        app.global_script='path-js/global-config';
{#        app.controller='app/forum';#}
        app.mainScript = 'path-js/app';
        seajs.use(app.mainScript);

    </script>
{% endblock %}

app/templates/forum/submit.html
{% extends "base_new.html" %}

{% block title %}

    投稿
    菜鸟窝-国内领先专业的移动开发IT技能在线教育平台

{% endblock %}
{% block description %}{% endblock %}


{% block main_block %}

<div id="content-container" class="container">


    <div class="row">

        <div class="col-md-12">


                <div class="submit-section cniao-section">

                       <div class="text-line" style="padding: 10px 0px; border-bottom: 1px solid #e0e0e0">
                                <h5>
                                    推荐文章
                                    <div class="line"></div>
                                </h5>
                                <div class="subtitle">感谢分享，文章的审核时间约1-2个工作日</div>
                            </div>


                    <form id="submit-thread-form"
                          class="submit-thread-form form-horizontal"
                          data-forum-id="{{ forum_id }}"
                          data-url="{{ url_for(".forum_thread_submit_request") }}"
                          data-go="{{ url_for(".forum_thread_submit_result",id=forum_id) }}"
                          >



                        <div class="form-group">
                             <div class="controls">
                                <input type="text" name="thread[title]" placeholder="文章标题"  class="form-control input-lg">
                            </div>

                        </div>

                        <div class="form-group">
                             <div class="controls">
                                <input type="text" name="thread[url]" placeholder="文章URL,暂只支持菜鸟窝下的文章"  class="form-control input-lg">

                             </div>

                        </div>
                        <div class="form-group">
                             <div class="controls text-center">
                                 <button id="submit-btn" type="submit" class="btn btn-lg btn-block  btn-primary ">投稿</button>
                             </div>
                        </div>


                    </form>


                </div>

        </div>
    </div>


</div>



{% endblock %}

{% block custom_js_block %}

    <script type="text/javascript">
     var CKEDITOR_BASEPATH ="/static/libs/ckeditor/4.4.8/";
        var app={};
        app.jsPaths={};
        app.global_script='path-js/global-config';
        app.controller='app/forum';
        app.mainScript = 'path-js/app';
        seajs.use(app.mainScript);

    </script>
{% endblock %}

app/templates/forum/write.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>


    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">

    <title> {% if action =='update'%}
        更新文章
    {% else %}
        创作中......
    {% endif %}

    菜鸟窝-国内领先专业的移动开发IT技能在线教育平台</title>
 <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='libs/bootstrap/3.3.0/css/bootstrap.min.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style_new.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/icon_style.css') }}"/>

    <link rel="shortcut icon" href="http://7mno4h.com1.z0.glb.clouddn.com/cniao.com.ico"/>




    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->



</head>

<body style="padding-top: 0px">
    <div class="cniao-wrap " style="background: #e6e6e6">

    <div   class="container">

{#        <buttton id="upload-img-btn">选择文章</buttton>#}

        <div class="row">

                    <div class="col-md-12">

                       <div class="write-form  cniao-section">
                        <form  id="thread-form"
                               data-forum-id="{{ forum_id }}"
                               data-thread-id="{{ thread.id }}"
                               data-create-url="{{ url_for('forum.thread_create') }}"
                               data-update-url="{{ url_for('forum.thread_modify') }}"
                               data-thread-type="{{ thread_type }}"
                               data-action="{{ action }}"
                        >

                            <div class="title form-group">

                                <div class="controls">

                                    <input id="thread_title" type="text" name="thread[title]" placeholder="点击这里输入标题" value="{{thread.title if thread.title != None }}">
                                </div>

                            </div>

                            <div class="content form-group" id="thread-write-content">

                                <div class="controls">
                                    <div class="help-block"></div>

                                    <div id="editor-container" data-img-upload-token-url="{{ url_for('common.get_qiniu_upload_token',bucket='cniao5-imgs') }}">

                                            <textarea id="thread_content"
                                                name="thread[content]"
                                                class="form-control"
                                                rows="20"
                                            >

                                        {% if action=='update' %}
                                            {{ thread.content }}
                                        {% endif %}
                                    </textarea>
                                    </div>
                                </div>

                            </div>




                            <div class="action">

                                <div class="container">

                                    <div class="brief">

                                          <textarea
                                            id="thread_brief"
                                            name="thread[brief]"
                                            rows="2"
                                            class="form-control"
                                            placeholder="摘要 如果不填写会默认抓取正文前200个字"

                                            >{{thread.brief if thread.brief != None }}</textarea>




                                    </div>

                                     <span class="ml10 mr25">

                                        <span class="cniao-checkbox icon icon-checkbox-uncheck"></span> 原创

                                     </span>


                                    <button id="thread-save-btn" type="submit" class="btn btn-xlg  btn-primary ">

                                        {% if action=='update' %}   更新 {% else %}  发布{% endif %}
                                    </button>
                                </div>

                            </div>

                        </form>

                       </div>

                    </div>

                </div>

    </div>

    </div>
</body>



  <script src="{{ url_for('static', filename='libs/sea/2.1.1/sea.js') }}"></script>
   <script src="{{ url_for('static', filename='libs/seajs-global-config.js') }}"></script>
  <script type="text/javascript">
     var CKEDITOR_BASEPATH ="/static/libs/ckeditor/4.4.8/";
        var app={};
        app.jsPaths={};
        app.global_script='path-js/global-config';
        app.controller='app/thread-write';
        app.mainScript = 'path-js/app';
        seajs.use(app.mainScript);

    </script>