app/common/__init__.py
# -*- coding: UTF-8 -*-
from flask import Blueprint

__author__ = 'Ivan'

common = Blueprint('common', __name__)

from . import views

app/common/views.py
# -*- coding: UTF-8 -*-
import uuid

from flask import redirect, request, render_template, url_for, Response, jsonify
from flask.ext.login import login_required
from flask.ext.restful import abort
from app.common import common
from app.dao.user_dao import UserDao
from app.storage import q


__author__ = 'Ivan'


@common.route('/qn/upload/token/<string:bucket>')
def get_qiniu_upload_token(bucket):
    token = q.upload_token(bucket)
    return jsonify(uptoken=token)



@common.route('/file/key')
def build_file_key():
    key_name = '%s' % (uuid.uuid1())

    return jsonify(result=key_name)



@common.route('/user/<int:id>/profile/complete/check')
def check_user_profile_complete(id):

    user_dao = UserDao()

    user = user_dao.get(id)

    if user is None:
        return jsonify(result=False,message=u'用户不存在')


    is_email_full = True
    if user.email is None or user.email=='':
        is_email_full=False


    is_head_logo_full = True
    if user.logo_url is None or user.logo_url=='':
        is_head_logo_full=False

    is_mobi_full = True
    if user.mobi is None or user.mobi=='':
        is_mobi_full=False

    is_qq_full = True
    if user.qq is None or user.qq=='':
        is_qq_full=False

    is_username_full = True
    if user.username is None or user.username=='':
        is_username_full=False



    return jsonify(result=True,message=u'success',
                   email=is_email_full,
                   mobi = is_mobi_full,
                   head=is_head_logo_full,
                   qq=is_qq_full,
                   username=is_username_full)


@common.route('/tool/image/upload')
def imgage_upload():
    return  render_template('common/image-upload.html')

app/templates/common/image-upload.html
{#<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"#}
{#        "http://www.w3.org/TR/html4/loose.dtd">#}
<html>
<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>

     <script src="{{ url_for('static', filename='libs/jquery/jquery-1.10.2.min.js') }}"></script>
     <script src="{{ url_for('static', filename='libs/plupload/plupload.full.min.js') }}"></script>
     <script src="{{ url_for('static', filename='libs/qiniu/qiniu.min.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/icon_style.css') }}"/>

    <style type="text/css">


        .images{
            background: #fff;
            padding: 20px;
            overflow: hidden;
        }


        ul, li {
            list-style: none;
            padding: 0;
            margin: 0;
        }


            .ul_pics li{float:left;width:80px;height:80px;margin:0 8px 8px 0;position: relative}
            .ul_pics li img{width:100%;height: 100%}
            .ul_pics li.img.active{
                border: 2px solid #46c37b;
            }

            .progress{position:relative;padding: 1px; border-radius:3px; margin:30px 0 0 0;}
            .bar{background-color: #46c37b; display:block; width:0%; height:20px; border-radius:3px;}
            .percent{position:absolute; height:20px; display:inline-block;top:3px; left:2%; color:#fff}








    </style>



</head>
<body>

    <div class="images" id="container" data-token-url="{{ url_for('common.get_qiniu_upload_token',bucket='cniao5-imgs') }}">


        <ul class="ul_pics" id="ul_pics">

            <li id="pickfiles">
                <img src="{{ url_for('static', filename='images/image_add.png') }}" alt="">
            </li>


        </ul>


    </div>

    <script>



        var tokenUrl = $("#container").data("token-url")

        var uploader = Qiniu.uploader({
                            runtimes: 'html5,flash,html4',    //上传模式,依次退化
                            browse_button: 'pickfiles',       //上传选择的点选按钮，**必需**
                            uptoken_url: tokenUrl,            //Ajax请求upToken的Url，**强烈建议设置**（服务端提供）
                             unique_names: true, // 默认 false，key为文件名。若开启该选项，SDK为自动生成上传成功后的key（文件名）。
                            // save_key: true,   // 默认 false。若在服务端生成uptoken的上传策略中指定了 `sava_key`，则开启，SDK会忽略对key的处理
                            domain: 'http://cniao5-imgs.qiniudn.com/',   //bucket 域名，下载资源时用到，**必需**
                            get_new_uptoken: false,  //设置上传文件的时候是否每次都重新获取新的token
                            container: 'container',           //上传区域DOM ID，默认是browser_button的父元素，
                            max_file_size: '100mb',           //最大文件体积限制
                            flash_swf_url: '/static/libs/plupload/Moxie.swf',  //引入flash,相对路径
                            max_retries: 3,                   //上传失败最大重试次数
                            dragdrop: true,                   //开启可拖曳上传
                            drop_element: 'container',        //拖曳上传区域元素的ID，拖曳文件或文件夹后可触发上传
                            chunk_size: '4mb',                //分块上传时，每片的体积
                            auto_start: true,                 //选择文件后自动上传，若关闭需要自己绑定事件触发上传
                            filters: {
                                max_file_size: '1mb',
                                mime_types: [
                                    { title: "Image files", extensions: "jpg,gif,png" }
                                ]
                            },
                            init: {
                                'FilesAdded': function(up, files) {


                                        var li = '';
                                        plupload.each(files, function(file) { //遍历文件
                                            li += "<li class='img' id='" + file['id'] + "'><div class='progress'><span class='bar'></span><span class='percent'>0%</span></div></li>";
                                        });
                                        //$("#ul_pics").prepend(li);
                                        $("#ul_pics").append(li);

                                },
                                'BeforeUpload': function(up, file) {
                                       // 每个文件上传前,处理相关的事情
                                },
                                'UploadProgress': function(up, file) {

                                    var percent = file.percent;
                                    $("#" + file.id).find('.bar').css({"width": percent + "%"});
                                    $("#" + file.id).find(".percent").text(percent + "%");

                                },
                                'FileUploaded': function(up, file, info) {

                                    var res = JSON.parse(info)
                                    var domain = up.getOption('domain');
                                    var sourceLink = domain + res.key; //获取上传成功后的文件的Url

                                    $("#" + file.id).html("<img  src='" + sourceLink + "'/>");

                                },
                                'Error': function(up, err, errTip) {
                                       //上传出错时,处理相关的事情
                                },
                                'UploadComplete': function() {
                                       //队列文件处理完毕后,处理相关的事情
                                }

                            }
                        });


        $("#ul_pics").on('click',"li.img",function(){

            var this_ = $(this);

            this_.toggleClass('active')

        })


    </script>


</body>

</html>